spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fisheye_moviesys?useUnicode=true&characterEncoding=utf-8&userSSL=false&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 200512
